language: java
jdk:
  - oraclejdk7
  - openjdk7

install:
    - TERM=dumb cd VWorkflows-FX; ./gradlew --refresh-dependencies --stacktrace

script:
    - TERM=dumb cd VWorkflows-FX; ./gradlew build --stacktrace
