sudo: false

language: java
install: true
jdk: oraclejdk8

env:
  matrix:
  - TERM=dumb

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

before_script:
  - ./gradlew --version
  
script:
    - TERM=dumb ./gradlew build -S -x :vworkflows-demo:jfxJar

after_success:
  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
