sudo: false

language: java
jdk:
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"

install:
    - TERM=dumb ./gradlew --refresh-dependencies --stacktrace

before_script:
  - ./gradlew --version

script:
    - TERM=dumb ./gradlew build --stacktrace -x :sample-javafx-groovy:jfxJar

after_success:
  - TERM=dumb ./gradlew clean test jacocoTestReport coveralls --stacktrace
